"""add unique team leader constraint"""

revision = '1712ddbf6048'
down_revision = 'af0d5e3bdbda'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_team_event_leader', 'teams', ['event_id', 'leader_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_event_leader', 'teams', type_='unique')
    # ### end Alembic commands ###

