"""test migration"""

revision = '6de170f3cfe0'
down_revision = '0002_add_team_member_qr_code_path'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    op.add_column(
        'registrations',
        sa.Column(
            'payment_status',
            sa.String(20),
            nullable=False,
            server_default='pending',
        )
    )

    op.add_column(
        'registrations',
        sa.Column(
            'payment_id',
            sa.String(255),
            nullable=True,
        )
    )

    op.add_column(
        'registrations',
        sa.Column(
            'amount_paid',
            sa.Float(),
            nullable=False,
            server_default='0',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'amount_paid')
    op.drop_column('registrations', 'payment_id')
    op.drop_column('registrations', 'payment_status')
    # ### end Alembic commands ###

