"""add paid event fields"""

revision = '8b880ad087ac'
down_revision = '6de170f3cfe0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    op.add_column(
        'events',
        sa.Column(
            'is_paid_event',
            sa.Boolean(),
            nullable=False,
            server_default='0',
        )
    )

    op.add_column(
        'events',
        sa.Column(
            'registration_fee',
            sa.Float(),
            nullable=False,
            server_default='0',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'registration_fee')
    op.drop_column('events', 'is_paid_event')
    # ### end Alembic commands ###

